import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/theme-provider";
import { geistSans, geistMono } from "@/components/fonts";

export const metadata: Metadata = {
  title: "EventMinder",
  description: "Generated by Prabhjot Singh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:text-gray-100 text-zinc-800 dark:bg-gray-900 bg-zinc-300`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
