import { SessionProvider } from "@/components/assets/SessionProvider";
import Providers from "@/components/assets/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "EventMinder",
  description: "Generated by Prabhjot Singh and rashi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-1 h-screen flex-col dark:text-gray-100 text-zinc-800 dark:bg-sky-950 bg-blue-100`}
      >
        <SessionProvider>
          <Providers>
            {children}
            <Toaster/>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
